#Use the official MySQL Image as base
FROM mysql:latest

# Set the working directory to /app
WORKDIR /app

# Copy/ Add the current directory contents into the container at /app
ADD . /app/

# Set the default user for the MySQL image
RUN useradd -ms /bin/bash krishna

USER krishna

# SET the environment variables for the new user
ENV MySQL_USER=external_user
ENV MySQL_PASSWORD=password
ENV MySQL_DATABASE=my_database

# Run the following commands to create the new user and grant it the necessary privileges
#RUN mysql -u root -p -e "CREATE USER '$MySQL_USER'@'%'IDENTIFIED BY '$MySQL_PASSWORD';"
#RUN mysql -u root -p -e  "GRANT ALL PRIVILEGES ON $MySQL_DATABASE.* TO '$MYSQL_USER'@'%';"
#RUN mysql -u root -p -e "FLUSH PRIVILEGES;"

# Expose port 3306 to allow connections to the database
EXPOSE 3306:3306

# Start the mysql server when the container is run
CMD [ "mysqld" ]
